
pagetitle: MPX NYC

project:
  type: book
  resources:
    - "CNAME"
  
pdf-engine: pdflatex

    
execute: 
  message: false
  warning: false
  echo: true
  
preview: 
  watch-inputs: true
    
    
    
    
format:
  html:
    image: "_const/images/image_mpxnyc.png"
    include-in-header:
      text: |
        <style>
        .quarto-title-meta-heading { display: none; }
        .quarto-title-meta-contents { display: none; }
        </style>
    title-block-style: none
    embed-resources: false
    font: "Helvetica Neue"
    grid: 
      gutter-width: 3.5em
    theme: "_const/custom_theme.scss"
    code-fold: true
    code-overflow: wrap
    code-tools: 
      source: false
      toggle: true
    code-block-bg: true
    code-block-border-left: "#FF99C5"
    code-link: true
    number-depth: 3
    crossrefs-hover: true

  

bibliography: "_const/bibliography.bib"
reference-location: margin
citation-location: margin

title-block-style: none

crossref:
  appendix-title: " "
  appendix-delim: " -"

book:
  repo-url: "https://github.com/mpxnyc/community_connection_report"
  repo-branch: "production"
  favicon: "_const/images/image_mpxnyc.png"
  repo-actions: [source]
  repo-link-target: "_blank"
  bread-crumbs: true
  google-analytics: "G-8EDGL4274R"
  cookie-consent: true
  page-footer: 
    left: "Copyright 2025, Ctrl+F" 
    right: 
      - icon: github
        href: "https://github.com/orgs/mpxnyc/repositories"
  sidebar:
    search: true
    title: ""
    style: floating
    collapse-level: 1
    logo: "_const/images/image_mpxnyc.png"
    
  chapters:
  - "index.qmd"
  - "1_contents.qmd"
  - "2_intro.qmd"
  - part: "Methods"
    chapters:
    - "3_data_methods.qmd"
    - "4_measures.qmd"
    - "5_analysis.qmd"
  - part: "Results"
    chapters:
      - "6_people.qmd"
      - "7_gatherings.qmd"
      - "8_movement.qmd"
      - "9_mixing.qmd"
      - "10_outbreaks.qmd"
  - part: "Discussion"
    chapters:
      - "11_discussion.qmd"
  appendices: 
      - "A_context.qmd"
      - "B_description.qmd"
      - "C_causality.qmd"
      - "D_organizing.qmd"
      - "E_marketing.qmd"
      - "F_measurement.qmd"
      - "G_results.qmd"





