---
toc: false
sidebar: false
title-block-style: none
format:
  html:
    toc: false
    css: _const/custom_index.scss

---




```{r packages, eval = FALSE}

install.packages(c(
  "cowplot",
  "dplyr",
  "ggforce",
  "ggimage",
  "ggplot2",
  "ggraph",
  "grid",
  "gt",
  "gtsummary",
  "here",
  "igraph",
  "knitr",
  "labelled",
  "latex2exp",
  "lubridate",
  "magick",
  "purrr",
  "remotes",
  "rlang",
  "scales",
  "sf",
  "stringr",
  "targets",
  "tidygraph",
  "tidyjson",
  "tidyr",
  "uuid"
))

remotes::install_github("mpxnyc/mpxnyc")
```



```{r process_data}
#| output: false

targets::tar_make(reporter = "silent") # Run data pipeline

```




```{r}
targets::tar_source("R_functions") # Access custom defined functions
```

```{r cache, include=FALSE, eval=TRUE}

knitr::opts_chunk$set(cache = TRUE, cache.path = "_cache/index/")
```


{{< include __0_index/hero.qmd >}}




{{< include __0_index/welcome.qmd >}}




{{< include __0_index/open_science.qmd >}}

{{< include __0_index/why_matters.qmd >}}

{{< include __0_index/who_we_are.qmd >}}

{{< include __0_index/why_self_publish.qmd >}}

{{< include __0_index/impact.qmd >}}


{{< include __0_index/fine_text.qmd >}}

# Home {.hidden .unnumbered }


